config:
  credentials: []
  project_repos:
    github.com/EOSC-synergy/sqaaas-tooling:
      branch: main
      repo: https://github.com/EOSC-synergy/sqaaas-tooling
    github.com/mychem/mychem-code:
      branch: master
      repo: https://github.com/mychem/mychem-code.git
environment:
  JPL_DOCKERFORCEBUILD: enabled
  JPL_KEEPGOING: enabled
sqa_criteria:
  QC.Acc:
    repos:
      github.com/mychem/mychem-code git:
        commands:
        - /usr/bin/env sh .sqa/script.foggy-vermilion-uguisu.sh
        container: qc.acc_scanty-tangerine-zebu
  QC.Doc:
    repos:
      github.com/mychem/mychem-code find_doc_files.py:
        commands:
        - /usr/bin/env sh .sqa/script.hilly-russet-ragdoll.sh
        container: qc.doc_wheezy-orchid-affenpinscher
      github.com/mychem/mychem-code git:
        commands:
        - /usr/bin/env sh .sqa/script.shaky-brown-flamingo.sh
        container: qc.doc_nippy-amethyst-chihuahua
      github.com/mychem/mychem-code restructuredtext-lint:
        commands:
        - /usr/bin/env sh .sqa/script.wheezy-pear-chihuahua.sh
        container: qc.doc_wimpy-chartreuse-newt
  QC.Lic:
    repos:
      github.com/mychem/mychem-code licensee:
        commands:
        - /usr/bin/env sh .sqa/script.crappy-orchid-moth.sh
        container: qc.lic_cloudy-charcoal-alligator
  QC.Met:
    repos:
      github.com/mychem/mychem-code validate_codemeta:
        commands:
        - /usr/bin/env sh .sqa/script.cranky-rust-anteater.sh
        container: qc.met_frumpy-cornflower-earwig
  QC.Sty:
    repos:
      github.com/mychem/mychem-code jsonlint:
        commands:
        - /usr/bin/env sh .sqa/script.wiggy-ecru-retriever.sh
        container: qc.sty_beady-violet-markhor
      github.com/mychem/mychem-code oclint:
        commands:
        - /usr/bin/env sh .sqa/script.craggy-ochre-bear.sh
        container: qc.sty_stealthy-turquoise-falcon
  QC.Ver:
    repos:
      github.com/mychem/mychem-code get_git_tags.py:
        commands:
        - /usr/bin/env sh .sqa/script.cozy-wheat-hornet.sh
        container: qc.ver_sleazy-celadon-chin
timeout: 5400
