config:
  credentials: []
  project_repos:
    github.com/EOSC-synergy/sqaaas-tooling:
      branch: main
      repo: https://github.com/EOSC-synergy/sqaaas-tooling
    github.com/mychem/mychem-code:
      branch: master
      repo: https://github.com/mychem/mychem-code.git
environment:
  JPL_DOCKERFORCEBUILD: enabled
  JPL_KEEPGOING: enabled
sqa_criteria:
  QC.Acc:
    repos:
      github.com/mychem/mychem-code git:
        commands:
        - /usr/bin/env sh .sqa/script.hilly-periwinkle-cat.sh
        container: qc.acc_breezy-burgundy-goat
  QC.Doc:
    repos:
      github.com/mychem/mychem-code find_doc_files.py:
        commands:
        - /usr/bin/env sh .sqa/script.droopy-rust-ragdoll.sh
        container: qc.doc_muzzy-charcoal-frigatebird
      github.com/mychem/mychem-code git:
        commands:
        - /usr/bin/env sh .sqa/script.crabby-taupe-wolverine.sh
        container: qc.doc_stuffy-platinum-goat
      github.com/mychem/mychem-code restructuredtext-lint:
        commands:
        - /usr/bin/env sh .sqa/script.crappy-amber-goat.sh
        container: qc.doc_sleazy-xanthic-tetra
  QC.Lic:
    repos:
      github.com/mychem/mychem-code licensee:
        commands:
        - /usr/bin/env sh .sqa/script.dorky-ivory-angelfish.sh
        container: qc.lic_skinny-magenta-ragdoll
  QC.Met:
    repos:
      github.com/mychem/mychem-code validate_codemeta:
        commands:
        - /usr/bin/env sh .sqa/script.wheezy-yellow-lemming.sh
        container: qc.met_freaky-alizarin-crab
  QC.Sty:
    repos:
      github.com/mychem/mychem-code jsonlint:
        commands:
        - /usr/bin/env sh .sqa/script.droopy-peach-owl.sh
        container: qc.sty_sloppy-apricot-malamute
      github.com/mychem/mychem-code oclint:
        commands:
        - /usr/bin/env sh .sqa/script.skinny-flax-zonkey.sh
        container: qc.sty_shaggy-crimson-foxhound
  QC.Ver:
    repos:
      github.com/mychem/mychem-code get_git_tags.py:
        commands:
        - /usr/bin/env sh .sqa/script.beady-chocolate-turkey.sh
        container: qc.ver_trippy-coral-quoll
timeout: 5400
